import { readFile, writeFile } from "node:fs/promises";
import { Data, Effect } from "effect";
import type { FreeTextColumn } from "../domain/engagement";
import type { ResponseVerdict } from "./aggregate";
import type { SurveyResponse } from "./ingest";

/**
 * What `opt_in_contact` licenses us to do with a volunteer's words.
 *
 * Three states, not two, because the export has three: 234 responses say yes,
 * 46 say no, and 104 say nothing at all. Collapsing the blanks into either
 * answer is the whole problem — treat them as yes and we attribute a grant
 * quote to someone who never agreed; treat them as no and we silently discard
 * a quarter of Karen's stated top need. `needs_check` is the honest third
 * state, and it is a question for a human rather than a verdict.
 */
export type Consent = "granted" | "needs_check" | "declined";

/**
 * Read one response's consent.
 *
 * Pure and total over all three states `ingest` can produce. `optInContact` is
 * already tri-state coming out of `ingest`, which maps anything that is not a
 * literal "yes" or "no" — a typo, a stray "Y", a value JA adds later — to
 * `null`. That means an unrecognised value lands in `needs_check` rather than
 * in `granted`, which is the direction an unknown should fall in when the cost
 * of being wrong is a consent violation.
 */
export function consentOf(response: SurveyResponse): Consent {
  if (response.optInContact === true) return "granted";
  if (response.optInContact === false) return "declined";
  return "needs_check";
}

/**
 * One quotable sentence, with everything needed to attribute it.
 *
 * Shape locked in PRD #1 §Implementation Decisions. `consent` is the two-state
 * narrowing of `Consent`: `declined` cannot appear here, because a declined
 * response never produces a candidate at all (PRD #1 §No-gos — no quote used
 * from a volunteer who declined contact). The type says so, so a downstream
 * consumer cannot write a branch for a case that does not exist.
 */
export type QuoteCandidate = {
  responseId: string;
  quote: string;
  sourceColumn: FreeTextColumn;
  volunteerName: string;
  program: string;
  consent: Exclude<Consent, "declined">;
};

/**
 * Collect every quotable sentence the model found, minus everyone who said no.
 *
 * Two inputs rather than one because the judgement and the attribution live in
 * different places: quotability is on the sentence verdicts, and the
 * volunteer's name and program are on the survey row. Neither type carries the
 * other's half.
 *
 * Reads `verdicts`, never `signal`. A response whose signal is `none` is not a
 * lead, and this stream does not care — it is a library, not a handoff, and
 * the best line in the export may well come from someone with no intention of
 * coming back.
 */
export function extractQuotes(
  rows: SurveyResponse[],
  verdicts: ResponseVerdict[],
): QuoteCandidate[] {
  const byId = new Map(rows.map((row) => [row.responseId, row]));
  const candidates: QuoteCandidate[] = [];

  for (const verdict of verdicts) {
    const row = byId.get(verdict.responseId);
    if (row === undefined) {
      throw new Error(
        `${verdict.responseId} has a verdict but no survey row; a quote cannot be attributed`,
      );
    }

    const consent = consentOf(row);
    if (consent === "declined") continue;

    for (const sentence of verdict.verdicts) {
      if (sentence.quotable !== true) continue;
      candidates.push({
        responseId: verdict.responseId,
        quote: sentence.quote,
        sourceColumn: sentence.column,
        volunteerName: row.volunteerName,
        program: row.program,
        consent,
      });
    }
  }

  return candidates;
}

export const USABLE_HEADING = "## Usable";
export const NEEDS_CHECK_HEADING = "## Needs consent check";

const PREAMBLE = `# Volunteer quotes

A running document for Karen and the grants team, appended to on every run.
Nothing here is ever edited or removed — a quote already collected is not
re-added, and a quote already written down stays written down.

Generated by \`src/pipeline/quotes.ts\`. Edit that, not this.
`;

const NEEDS_CHECK_NOTE = `
These volunteers left \`opt_in_contact\` blank, so nobody has said yes and
nobody has said no. Ask before using one of these in anything published.
`;

/**
 * The identity of a collected quote.
 *
 * `(responseId, sourceColumn, quote)` rather than `responseId` alone, because a
 * response can contribute several sentences and each is separately usable. The
 * quote text is part of the key on purpose: it makes the key survive the
 * re-numbering case PRD #1 §Open Questions settled for the ledger. A renumbered
 * `JA-24001` carrying different prose is a different quote and should be
 * collected; the same prose under a new id is the same quote and should not.
 */
export function quoteKey(candidate: QuoteCandidate): string {
  return `${candidate.responseId}::${candidate.sourceColumn}::${candidate.quote}`;
}

const KEY_MARKER = /^<!-- quote-key: (.+) -->$/gm;

/**
 * Every quote the document already holds.
 *
 * Read back from a machine marker rather than by re-parsing the prose, so the
 * dedup does not depend on how the entry is formatted — the layout below can
 * change without silently re-collecting the whole history. The key is embedded
 * as JSON so a quote containing a newline or a quotation mark still occupies
 * exactly one line and round-trips byte-for-byte.
 */
export function collectedKeys(document: string): Set<string> {
  const keys = new Set<string>();

  for (const [line, encoded] of document.matchAll(KEY_MARKER)) {
    // A marker we cannot read is a hole in the dedup, and a hole in the dedup
    // re-surfaces quotes Karen has already worked through — the failure that
    // makes her stop trusting the document. Skipping it would leave no trace;
    // throwing names the line.
    const key = encoded === undefined ? undefined : tryParseKey(encoded);
    if (key === undefined) {
      throw new Error(`quotes document has an unreadable quote-key marker: ${line}`);
    }
    keys.add(key);
  }

  return keys;
}

function tryParseKey(encoded: string): string | undefined {
  try {
    const parsed: unknown = JSON.parse(encoded);
    return typeof parsed === "string" ? parsed : undefined;
  } catch {
    return undefined;
  }
}

/**
 * The candidates this document does not already hold, in the order given.
 *
 * Deduplicates against the batch as well as against the document, because one
 * export can legitimately yield the same key twice — the same sentence reached
 * by two verdicts, or an operator passing a concatenation of two runs. Both
 * `renderQuotesDocument` and `appendQuotes` need this answer, and they must
 * agree: the count reported to the operator and the entries written to the file
 * come from one call, so "added 2" can never sit beside a document that gained
 * one.
 */
export function uncollected(document: string, candidates: QuoteCandidate[]): QuoteCandidate[] {
  const seen = collectedKeys(document);
  const fresh: QuoteCandidate[] = [];

  for (const candidate of candidates) {
    const key = quoteKey(candidate);
    if (seen.has(key)) continue;
    seen.add(key);
    fresh.push(candidate);
  }

  return fresh;
}

function entry(candidate: QuoteCandidate): string {
  const quoted = candidate.quote
    .split("\n")
    .map((line) => `> ${line}`)
    .join("\n");

  return [
    `<!-- quote-key: ${JSON.stringify(quoteKey(candidate))} -->`,
    quoted,
    "",
    `— **${candidate.volunteerName}** · ${candidate.program} · \`${candidate.sourceColumn}\` · ${candidate.responseId}`,
    "",
  ].join("\n");
}

/**
 * Add this run's new quotes to the running document.
 *
 * Pure: takes the document as text and returns the next one, so the
 * append-only property is testable without touching a filesystem.
 *
 * Append-only in the strict sense — every byte of `existing` survives into the
 * result, and the only edits are insertions. That is what makes the document
 * safe to hand to the grants team: a quote they have already pulled into a
 * proposal cannot vanish because a later run classified its sentence
 * differently.
 *
 * A non-empty document missing either heading is a hard failure rather than a
 * fresh start. Rebuilding from the preamble would discard however many weeks of
 * collected quotes the file held, which is the one outcome this module exists
 * to make impossible.
 */
export function renderQuotesDocument(existing: string, candidates: QuoteCandidate[]): string {
  const base =
    existing.trim() === ""
      ? `${PREAMBLE}\n${USABLE_HEADING}\n\n${NEEDS_CHECK_HEADING}\n${NEEDS_CHECK_NOTE}`
      : existing;

  const usableAt = base.indexOf(USABLE_HEADING);
  const needsCheckAt = base.indexOf(NEEDS_CHECK_HEADING);
  if (usableAt === -1 || needsCheckAt === -1) {
    throw new Error(
      `quotes document is missing "${USABLE_HEADING}" or "${NEEDS_CHECK_HEADING}"; refusing to rewrite it`,
    );
  }

  const fresh = uncollected(base, candidates);
  if (fresh.length === 0) return base;

  const usable = fresh
    .filter((c) => c.consent === "granted")
    .map(entry)
    .join("\n");
  const needsCheck = fresh
    .filter((c) => c.consent === "needs_check")
    .map(entry)
    .join("\n");

  // The usable group is inserted at the end of its own section rather than
  // appended to the file, so the two groups stay groups as the document grows.
  const head = base.slice(0, needsCheckAt).trimEnd();
  const tail = base.slice(needsCheckAt).trimEnd();

  return [
    usable === "" ? head : `${head}\n\n${usable.trimEnd()}`,
    needsCheck === "" ? tail : `${tail}\n\n${needsCheck.trimEnd()}`,
  ]
    .join("\n\n")
    .concat("\n");
}

export class QuotesError extends Data.TaggedError("QuotesError")<{
  readonly path: string;
  readonly reason: string;
}> {}

/** Where the running document lives, relative to the repo root. */
export const QUOTES_PATH = "quotes.md";

/**
 * Add this run's quotes to the document on disk, and report what was new.
 *
 * The only impure function here — read, render, write — so everything that
 * decides *what* the document says stays testable without a filesystem.
 *
 * A missing file is the first run, not an error: the document does not exist
 * until there is a quote to put in it. Every other read failure is real and
 * propagates, because the alternative is treating an unreadable document as an
 * empty one and writing a fresh preamble over weeks of collected quotes.
 *
 * Returns the newly added candidates rather than void, so a caller can say how
 * many quotes this week produced without diffing the file. Zero is a normal
 * answer on a re-run over an unchanged export.
 */
export function appendQuotes(
  path: string,
  candidates: QuoteCandidate[],
): Effect.Effect<QuoteCandidate[], QuotesError> {
  return Effect.tryPromise({
    try: () => readFile(path, "utf8"),
    catch: (cause) =>
      isNotFound(cause)
        ? new NoDocumentYet({})
        : new QuotesError({ path, reason: `could not read: ${String(cause)}` }),
  }).pipe(
    Effect.catchTag("NoDocumentYet", () => Effect.succeed("")),
    Effect.flatMap((existing) =>
      Effect.try({
        try: () => ({
          document: renderQuotesDocument(existing, candidates),
          added: uncollected(existing, candidates),
        }),
        catch: (cause) => new QuotesError({ path, reason: String(cause) }),
      }),
    ),
    Effect.flatMap(({ document, added }) =>
      Effect.tryPromise({
        try: () => writeFile(path, document, "utf8"),
        catch: (cause) => new QuotesError({ path, reason: `could not write: ${String(cause)}` }),
      }).pipe(Effect.as(added)),
    ),
  );
}

/** Internal: "the document does not exist yet", which is not a failure. */
class NoDocumentYet extends Data.TaggedError("NoDocumentYet")<Record<string, never>> {}

function isNotFound(cause: unknown): boolean {
  return (
    typeof cause === "object" &&
    cause !== null &&
    "code" in cause &&
    (cause as { code?: unknown }).code === "ENOENT"
  );
}
